### PR TITLE
Fx swap subgraph 20220824

### PR DESCRIPTION
**Pull request by ghost**
Added a new subgraph (2nd iteration)

### CODE REVIEW

**Comment by ghost** [comment]
Hi,

I would like to add another subgraph.

Thanks,

Issei

**Comment by ghost** [comment]
Hi @zakir-code,

Thank you for manually deploying the subgraph! 

I think there is an issue with the deployment, however - I think you deployed the wrong subgraph. I would like to deploy the below: 

565F168B-7621-4803-9B53-D23767C62F8A

Thanks again.

Issei

**Comment by zakir-web3** [comment]
https://github.com/FunctionX/fx-subgraph/runs/7989050354?check_suite_focus=true

**Comment by zakir-web3** [comment]
The directory name and json file name must be the same as the subgraph name

**Comment by ghost** [comment]
Thank you @zakir-code! 

I will make sure that the directory name and json file name matches the subgraph name! 

My apologies for making this mistake. Thank you for correcting! :-)

You have a nice day!

**Comment by ghost** [comment]
Hi @zakir-code,

Sorry to bother you again, but I am running into issues with the subgraph. I am seeing the below, and cannot query any data. 

Would you be able to re-deploy the subgraph again? 

Thank you! 

Issei

**Comment by zakir-web3** [comment]
let me check

**Comment by zakir-web3** [comment]
[graph-node-index](https://graph-node-index.functionx.io/graphql/playground?query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20start%20with%20a%20%22%7B%22%20character.%20Lines%20that%20starts%0A%23%20with%20a%20%23%20are%20ignored.%0A%23%0A%23%20An%20example%20GraphQL%20query%20might%20look%20like%3A%0A%23%0A%23%20%20%20%20%20%7B%0A%23%20%20%20%20%20%20%20field(arg%3A%20%22value%22)%20%7B%0A%23%20%20%20%20%20%20%20%20%20subField%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%0A%23%20Keyboard%20shortcuts%3A%0A%23%0A%23%20%20Prettify%20Query%3A%20%20Shift-Ctrl-P%20(or%20press%20the%20prettify%20button%20above)%0A%23%0A%23%20%20%20%20%20%20%20Run%20Query%3A%20%20Ctrl-Enter%20(or%20press%20the%20play%20button%20above)%0A%23%0A%23%20%20%20Auto%20Complete%3A%20%20Ctrl-Space%20(or%20just%20start%20typing)%0A%23%0A%0A%0A%7B%0A%20%20indexingStatusForCurrentVersion(subgraphName%3A%20%22subgraphFX2%22)%20%7B%0A%20%20%20%20synced%0A%20%20%20%20health%0A%20%20%20%20fatalError%20%7B%0A%20%20%20%20%20%20message%0A%20%20%20%20%20%20block%20%7B%0A%20%20%20%20%20%20%20%20number%0A%20%20%20%20%20%20%20%20hash%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20handler%0A%20%20%20%20%7D%0A%20%20%20%20chains%20%7B%0A%20%20%20%20%20%20chainHeadBlock%20%7B%0A%20%20%20%20%20%20%20%20number%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20latestBlock%20%7B%0A%20%20%20%20%20%20%20%20number%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by ghost** [comment]
Hi @zakir-code,

Thank you for pointing this out! 

I will double check my subgraph mappings now. :-)

Issei

**Comment by ghost** [comment]
Hi @zakir-code,

Thank you for your help earlier!!! 

I know this is becoming very repetitive for you, but could you please deploy the same subgraph one more time? 

I made my change to the subgraph mapping - I used the same address, but GIT has identified that it is now different. I think the issue might be the formatting of my address. 

Hopefully, this is the very last time the subgraph need to be deployed. 

Thanks,

Issei

**Comment by zakir-web3** [comment]
https://github.com/FunctionX/fx-subgraph/runs/7991862340?check_suite_focus=true

**Comment by ghost** [comment]
Hi @zakir-code,

I made another change again - this time to the subgraph.yaml file.
There was a formatting (indentation issue).

Could you please try once more? 

Thank you very much!!! 

Issei

**Comment by zakir-web3** [comment]
That's alright!

**Comment by ghost** [comment]
@zakir-code,

Thank you again for deploying - everything is now working!!! I think there was an issue with the string formatting in the subgraph mapping logic. 

I just had to make one very final change to my subgraph to calculate the price (liquidity provider count now ignored - because we have so little users at this stage). 

If you could deploy once more, that would be much appreciated. 

Thank you for all your help today. :-) :-)

Issei

**Comment by zakir-web3** [comment]
ok

**Comment by ghost** [comment]
Morning @zakir-code,

Thank you for your help yesterday! 

I was wondering whether you could re-deploy the subgraph again.

My apologies, but as per the team request, they want to see additional data, which was not part of the requirement before, so made one additional change to my subgraph mapping logic.

**Comment by zakir-web3** [comment]
no problem

**Comment by ghost** [comment]
Thank you @zakir-code!! 

Sorry to ask you again, but if you could re-deploy one more time, that would be much appreciated! 

This will be the final time for today - sorry for the multiple attempts, but because of the low liquidity/volume with tokens in FXSwap, certain logic required multiple reviews/revisions so that data can appear. 

The subgraph, originally from Uniswap, had no issues since their liquidity was in the millions - this is something which we do not have. They have a flag in the logic to only show data if liquidity > 1,000,000 USD (example). Also, we do not have DAI and USDC (yet) so I am making adjustments here to only use USDT numbers. 

Thanks again, and sorry for the trouble.

**Comment by zakir-web3** [comment]
It has been redeployed. You can upgrade the subgraph by modifying the `last_version` and `version` of the subgraph, and then submitting a pull request.

**Comment by ghost** [comment]
Thank you @zakir-code. 

`It has been redeployed. You can upgrade the subgraph by modifying the last_version and version of the subgraph, and then submitting a pull request.`

^ I am assuming this would still mean you have to manually run the script to deploy it, right? 

Would you be able to deploy the subgraph again? - I have modified the reserve0 with reserve1 (since Uniswap harcoded their variables). Thank you!!!!

**Comment by zakir-web3** [comment]
Yes, github action workflow deployment subgraph is triggered manually

**Comment by ghost** [comment]
Thanks for letting me know - in that case, I will try this now and see if the deployment is automatic!!

**Comment by zakir-web3** [comment]
There is currently no auto-deployment, as the deployed subgraph needs to be reviewed, and auto-deployment in some cases will be considered later

**Comment by ghost** [comment]
Thanks for letting me know @zakir-code. 
I think I misunderstood your explanation before.
I look forward to the auto-deployment if it is considered in the future. 
Would you be able to deploy the subgraph once more? I am getting wrong numbers from my subgraph hence I need to troubleshoot one more time. 
Thank you!

**Comment by zakir-web3** [comment]
I'd consider automating the deployment in the testnet first so you can debug quickly in the testnet. In order to ensure the security and stability of the mainnet environment, we are sorry that automated deployment is temporarily unavailable.

**Comment by ghost** [comment]
Thank you for your feedback as always, and no need for an apology!!! I should be the one apologising given that I have had to ask for so much help from you. 

Would you be able to deploy it once more? This will be the final today. I was given some help with the subgraph logic, and now should be okay. 

I will need to redeploy it once we bridge across USDC and DAI (after the governance proposal).

**Comment by zakir-web3** [comment]
OK 👌

**Comment by ghost** [comment]
You guys/girls are so pro!

**Comment by zakir-web3** [comment]
hahaha, this is the first time to get such a high rating🤓

**Comment by ghost** [comment]
You have such an awesome team in Shenzen. 
I am super thankful for all the help!

**Comment by ghost** [comment]
Hi @zakir-code,

Thank you for your help last week.
I would like you to deploy the subgraph once again because the AssemblyScript is not handling BigDecimal well. (1 * 0.00094445 becomes 0). 
If the change to the code does not work, I will revert it back. 

Thanks again.

**Comment by ghost** [comment]
Thank you @zakir-code - I would like to deploy this one more time with another change before I fully revert it back.
Thanks for your help as always.

**Pull request merged**
