### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by ghost**
My subgraph

### CODE REVIEW

**Comment by ghost** [comment]
I want to deploy my subgraph, which I have made for the Smart Contracts used by FXSwap to the Graph Node mainnet

**Comment by zakir-code** [comment]
Please resubmit the pull request and do not modify other files other than `subgraphFX2`

**Comment by zakir-web3** [comment]
- Deploying to Graph node 
Deployed to https://graph-node.functionx.io/subgraphs/name/subgraphFX2/graphql

- Subgraph endpoints:
Queries (HTTP):     https://graph-node.functionx.io/subgraphs/name/subgraphFX2
Subscriptions (WS): https://graph-node.functionx.io/ws/subgraphs/name/subgraphFX2

**Comment by zakir-web3** [comment]
https://github.com/FunctionX/fx-subgraph/runs/7688404486?check_suite_focus=true#step:4:156

**Comment by ghost** [comment]
Hi zakir-code,

Thank you very much - appreciate your help. 
I hope it did not take too long for you to complete! 👍

**Pull request merged**
